theme: jekyll-theme-cayman
plugins:
  - jekyll-relative-links
  
include:
  index.md
  panda.md
  kaltura.md

relative_links:
  enabled: true
  collections: true

title: [The title of your site]
description: [A short description of your site's purpose]
